name: Bot Run

on:
  schedule:
    - cron: '0 8 * * *'   # démarre à 8h tous les jours
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 360   # tourne 6 heures max

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Run Bot
        run: python bot.py
